services:
  app:
    build: .
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/amarDokan
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - IMAGE_UPLOAD_PATH=/app/uploads/img
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=amarDokan'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
