
spring.application.name=amarDokan

spring.datasource.url=jdbc:postgresql://localhost:5432/amarDokan
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.security.user.name=admin
spring.security.user.password=admin123


spring.mail.host=smtp.gmail.com
spring.mail.username=********@gmail.com
spring.mail.password=ylyi rrdm piut smbm # app password
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=8081

# Image Upload Path
image.upload.path=${IMAGE_UPLOAD_PATH:uploads/img}

